# -*- coding: utf-8 -*-
"""Proyecto Life Expectancy Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2kukFryEpzhqdjZwk04jnAO05bHTzxs

## 1. Introduction

La esperanza de vida es un indicador ampliamente utilizado para evaluar la salud y el bienestar general de las poblaciones. Se ve influenciada por múltiples factores, como las condiciones económicas, el acceso a la atención médica, la educación y la prevalencia de enfermedades.

El objetivo de este proyecto es explorar un conjunto de datos globales sobre esperanza de vida para identificar patrones, tendencias y relaciones entre esta y variables socioeconómicas y sanitarias clave. Mediante el análisis exploratorio de datos (AED), este proyecto busca comprender cómo diferentes factores pueden estar asociados con las variaciones en la esperanza de vida entre países y a lo largo del tiempo.

El análisis sigue un flujo de trabajo estructurado de ciencia de datos, que incluye la carga, la limpieza y el análisis exploratorio de datos, así como la elaboración de conclusiones. Los resultados de este estudio pueden ayudar a comprender mejor las desigualdades sanitarias globales y los factores que contribuyen a una vida más larga y saludable.

## 2. Carga de data

### 2.1 Librerias
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

"""### 2.2 Dataset"""

df = pd.read_csv("/content/Life Expectancy Data.csv")

df.head()

"""### 2.3 Forma del conjunto de datos"""

#Dimension del dataset
df.shape

#Información referente al numero de filas y columnas y tipos de datos
df.info()

#Nombres de columnas
df.columns

#Valores nulos (primer vistazo)
df.isnull().sum()

"""## 3. Limpieza de datos

###3.1 Copia del dataset (detalle pro)
"""

df_clean = df.copy()

"""###3.2 Revisión de valores nulos"""

df_clean.isnull().sum()

"""###3.3.1 Cálculo del porcentaje de valores nulos por variable"""

missing_percentage = (df_clean.isnull().sum() / len(df_clean)) * 100

missing_percentage = missing_percentage.sort_values(ascending=False)

missing_percentage

"""###3.3.2 Visualización"""

plt.figure(figsize=(10,6))
sns.barplot(
    x=missing_percentage.values,
    y=missing_percentage.index
)
plt.xlabel("Percentage of missing values (%)")
plt.ylabel("Variables")
plt.title("Missing Values Percentage by Variable")
plt.show()

"""###3.3.3 Identificación de variables a eliminar (>15%)"""

#Verificacion que no sea la variable objetivo (Life expectancy).
target = "Life expectancy "

variables_to_drop = [
    var for var in variables_to_drop if var != target
]

threshold = 15

variables_to_drop = missing_percentage[missing_percentage > threshold].index.tolist()

variables_to_drop

"""###3.3.4 Eliminación de variables"""

df_clean = df_clean.drop(columns=variables_to_drop)
df_clean

"""Para gestionar los datos faltantes, se calculó el porcentaje de valores faltantes para cada variable. Siguiendo las prácticas habituales en el análisis exploratorio de datos, se eliminaron del conjunto de datos las variables con más del 15 % de valores faltantes, ya que una proporción elevada de datos faltantes podría comprometer la fiabilidad del análisis.

###3.4 Imputación de valores faltantes restantes

🧠 Decisión metodológica (muy importante)

Para un EDA y análisis descriptivo:

Variables numéricas → mediana

Variables categóricas → moda
"""

#Identificar columnas por tipo
numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df_clean.select_dtypes(include=["object"]).columns

#Imputar variables numéricas
df_clean[numeric_cols] = df_clean[numeric_cols].fillna(
    df_clean[numeric_cols].median()
)

#Imputar variables categóricas
for col in categorical_cols:
    df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

"""Tras eliminar las variables con una alta proporción de valores faltantes, los datos faltantes restantes se procesaron mediante imputación. Las variables numéricas se imputaron utilizando la mediana, dada su robustez ante valores atípicos, mientras que las variables categóricas se imputaron mediante la moda. Este enfoque permite preservar el tamaño del conjunto de datos y, al mismo tiempo, reducir el posible sesgo introducido por los datos faltantes.

###3.5 Verificación final del dataset limpio
"""

#Verificar valores nulos
df_clean.isnull().sum()

#Verificar dimensión final
df_clean.shape

#Revisión final de tipos
df_clean.info()

"""Tras la limpieza de datos, se verificó el conjunto para garantizar la ausencia de valores faltantes y la consistencia de los tipos de datos. El conjunto de datos limpio ahora es apto para el análisis exploratorio.

## 4. Exploratory Data Analysis (EDA)

### 4.1 Distribución de la esperanza de vida
"""

#Distribución de la esperanza de vida
plt.figure(figsize=(8,5))
sns.histplot(df_clean["Life expectancy "], kde=True)
plt.title("Distribution of Life Expectancy")
plt.xlabel("Life Expectancy")
plt.ylabel("Frequency")
plt.show()

"""La distribución de la esperanza de vida muestra una concentración de valores en el rango superior, con una ligera asimetría. Esto sugiere mejoras en los resultados de salud a nivel mundial, aunque la variabilidad entre países sigue siendo evidente

### 4.2 Esperanza de vida a lo largo del tiempo
"""

life_by_year = df_clean.groupby("Year")["Life expectancy "].mean()

plt.figure(figsize=(8,5))
life_by_year.plot()
plt.title("Average Life Expectancy Over Time")
plt.xlabel("Year")
plt.ylabel("Life Expectancy")
plt.show()

"""Los resultados muestran una clara tendencia ascendente de la esperanza de vida media a lo largo del tiempo, lo que indica mejoras globales en las condiciones de salud y el nivel de vida durante el período analizado.

### 4.3 Relación entre los indicadores relacionados con el ingreso y la esperanza de vida
"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    x=df_clean["Income composition of resources"],
    y=df_clean["Life expectancy "],
    alpha=0.5
)
plt.title("Income Composition vs Life Expectancy")
plt.xlabel("Income composition of resources")
plt.ylabel("Life expectancy")
plt.show()

"""Los resultados sugieren una asociación positiva entre la composición de los ingresos de los recursos y la esperanza de vida. Los países con mayor composición de los ingresos tienden a presentar una mayor esperanza de vida.

En general, el análisis exploratorio de datos revela patrones consistentes entre la esperanza de vida y variables socioeconómicas y de salud clave. Los resultados destacan la importancia de los indicadores relacionados con los ingresos, la educación y las tasas de mortalidad para comprender las variaciones en la esperanza de vida entre países y a lo largo del tiempo.

Si bien algunas variables económicas, como el PIB, no pudieron analizarse debido a limitaciones en la integridad de los datos, indicadores alternativos proporcionaron información significativa sobre la relación entre las condiciones económicas y la salud de la población. Estos hallazgos sientan las bases para un enfoque analítico o predictivo más profundo en trabajos futuros.

##5.Análisis de correlación

###5.1.Analisis global de correlación
"""

#Preparación del dataset

# Seleccionar solo variables numéricas
df_numeric = df_clean.select_dtypes(include=["float64", "int64"])

# Ver cuántas variables entran
df_numeric.shape

plt.figure(figsize=(10, 8))
sns.heatmap(
    df_numeric.corr(),
    cmap="coolwarm",
    linewidths=0.8
)
plt.title("Global Correlation Matrix of Numerical Variables")
plt.show()

"""La matriz de correlación global utilizando todas las variables numéricas para obtener una visión general de las relaciones lineales dentro del conjunto de datos. Esta visualización permite identificar variables que presentan fuertes asociaciones con la esperanza de vida, así como una posible multicolinealidad entre las variables explicativas.

La matriz revela que la esperanza de vida está fuertemente correlacionada con varios indicadores socioeconómicos y de salud, en particular aquellos relacionados con las tasas de mortalidad, la educación y la composición de los ingresos. Con base en esta visión global, se seleccionó un subconjunto de variables con correlaciones más sólidas y significativas para un análisis más profundo.

"""

# Correlación con la variable objetivo
life_corr = df_numeric.corr()["Life expectancy "].sort_values(ascending=False)

life_corr

"""Las variables que presentan relaciones lineales más sólidas con la esperanza de vida para un análisis exploratorio y predictivo más profundo. Esta selección se basó en la magnitud de los coeficientes de correlación, considerando también la posible redundancia entre predictores altamente correlacionados.

###5.2. Modelo de regresion multiple
"""

# Correlación absoluta con la variable objetivo
corr_target = df_numeric.corr()["Life expectancy "].drop("Life expectancy ")

# Selección de variables con correlación relevante
selected_vars = corr_target[abs(corr_target) >= 0.3].index.tolist()

selected_vars

# Variable dependiente
y = df_clean["Life expectancy "]

# Variables independientes seleccionadas
X = df_clean[selected_vars]

# Agregar constante (intercepto)
X = sm.add_constant(X)

# Ajuste del modelo
model = sm.OLS(y, X).fit()

# Resumen del modelo
model.summary()

"""Se construyó un modelo de regresión lineal múltiple para evaluar el efecto conjunto de variables socioeconómicas y de salud seleccionadas sobre la esperanza de vida. Las variables explicativas se seleccionaron en función de su correlación absoluta con la variable objetivo, asegurando que solo se incluyeran las variables con asociaciones lineales significativas.

Los resultados del modelo indican que las variables relacionadas con la mortalidad presentan un impacto negativo significativo en la esperanza de vida, mientras que los indicadores relacionados con la educación y los ingresos muestran una asociación positiva y estadísticamente significativa. En general, el modelo demuestra una sólida capacidad explicativa, lo que destaca la relevancia de las variables seleccionadas para explicar las variaciones en la esperanza de vida.

###5.3.Refinamiento del modelo

👉 Regla estándar:

p < 0.05 → se queda

p ≥ 0.05 → candidata a eliminación
"""

# Extraer p-values (excluyendo la constante)
p_values = model.pvalues.drop("const")

# Variables significativas
significant_vars = p_values[p_values < 0.05].index.tolist()

significant_vars

"""El modelo de regresión inicial se perfeccionó eliminando las variables que no eran estadísticamente significativas al 5%. Este paso buscó mejorar la interpretabilidad del modelo, manteniendo al mismo tiempo su capacidad explicativa.

El modelo refinado incluye únicamente variables con contribuciones significativas a la esperanza de vida, lo que resulta en un modelo más sencillo e interpretable.
"""

# Nuevo modelo con variables significativas
X_refined = df_clean[significant_vars]
X_refined = sm.add_constant(X_refined)

refined_model = sm.OLS(y, X_refined).fit()

refined_model.summary()

"""###5.4.Diagnósticos del modelo"""

#Residuos vs valores ajustados
fitted_vals = refined_model.fittedvalues
residuals = refined_model.resid

plt.figure(figsize=(8,5))
sns.scatterplot(x=fitted_vals, y=residuals)
plt.axhline(0)
plt.xlabel("Fitted values")
plt.ylabel("Residuals")
plt.title("Residuals vs Fitted Values")
plt.show()

#Normalidad de residuos
sns.histplot(residuals, kde=True)
plt.title("Distribution of Residuals")
plt.show()

#Q-Q plot
sm.qqplot(residuals, line="45")
plt.title("Q-Q Plot of Residuals")
plt.show()

#Heterocedasticidad (Breusch–Pagan)
from statsmodels.stats.diagnostic import het_breuschpagan

bp_test = het_breuschpagan(residuals, X_refined)
labels = ["LM Statistic", "LM p-value", "F Statistic", "F p-value"]

dict(zip(labels, bp_test))

"""👉 Interpretación

p-value < 0.05 → heterocedasticidad presente

p-value ≥ 0.05 → homocedasticidad



De acuerdo con las pruebas diagnósticas para evaluar la validez de los supuestos de la regresión lineal. El análisis de residuos no muestra patrones sistemáticos sólidos, lo que sugiere un ajuste adecuado del modelo. La distribución de los residuos se aproxima a la normalidad, como lo respalda el gráfico Q-Q.

Se aplicó la prueba de Breusch-Pagan para evaluar la heterocedasticidad. Los resultados indican que existe heterocedasticidad [no significativa/alguna], lo cual debe tenerse en cuenta al interpretar los coeficientes del modelo.

## 6. Conclusions

Este estudio analizó los determinantes de la esperanza de vida mediante un análisis exploratorio estructurado de datos y un enfoque de regresión lineal múltiple. Tras depurar el conjunto de datos y seleccionar las variables relevantes con base en el análisis de correlación, se desarrolló un modelo de regresión refinado para mejorar la interpretabilidad y la significancia estadística.

Los resultados de la regresión confirman que las variables relacionadas con la mortalidad tienen un fuerte impacto negativo en la esperanza de vida, mientras que indicadores socioeconómicos como la educación y la composición de los ingresos influyen positivamente en los resultados de salud de la población. Los análisis de diagnóstico sugieren que el modelo cumple con los supuestos clave de la regresión lineal, lo que respalda la robustez de los hallazgos.

En general, este proyecto demuestra cómo la modelización estadística puede proporcionar información significativa sobre los factores asociados con la esperanza de vida. Investigaciones futuras podrían ampliar este trabajo incorporando técnicas avanzadas de modelización o enfoques de inferencia causal.
"""